# StudyValue - Analyzer設定ファイル
# Dart/Flutterコードの品質とスタイルを管理

# Flutter lintsルールセットを含める
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # 生成されたファイルを除外
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  # 厳格度設定
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # 基本的なlintルール
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    
    # 開発中のため許可
    avoid_print: false
    
    # コードスタイル
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    
    # パフォーマンス
    prefer_collection_literals: true
    prefer_spread_collections: true
    
    # 可読性
    use_string_buffers: true
    unnecessary_string_interpolations: true
