# StudyValue - コード解析設定（iOS専用最適化版）
# Dart/Flutterコードの品質とスタイルを管理
# iOS開発におけるベストプラクティスを適用

# Flutter公式のlintルールセットを基本として使用
include: package:flutter_lints/flutter.yaml

# アナライザー設定
analyzer:
  # 解析から除外するファイル・ディレクトリ
  exclude:
    # 自動生成ファイル（Hive、Riverpod等）
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    # iOSビルド成果物
    - "ios/Flutter/Generated.xcconfig"
    - "ios/Runner/GeneratedPluginRegistrant.*"
    # その他の生成ファイル
    - "build/**"
    - ".dart_tool/**"
  
  # 言語機能設定（型安全性の向上）
  language:
    # 厳格な型キャスト（実行時エラーを防ぐ）
    strict-casts: true
    # 厳格な型推論（型の明確性向上）
    strict-inference: true
    # 厳格な生の型チェック（ジェネリクスの安全性）
    strict-raw-types: true
  
  # エラー処理設定
  errors:
    # 重要な警告をエラーとして扱う
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error

# Lintルール設定（iOS開発最適化）
linter:
  rules:
    # === コンストラクタとオブジェクト生成 ===
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    
    # === iOS開発でのベストプラクティス ===
    # 開発効率向上（デバッグ時はprint文を許可）
    avoid_print: false
    
    # === コード品質向上 ===
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    
    # === パフォーマンス最適化 ===
    prefer_collection_literals: true
    prefer_spread_collections: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    
    # === 可読性向上 ===
    use_string_buffers: true
    unnecessary_string_interpolations: true
    unnecessary_string_escapes: true
    use_key_in_widget_constructors: true
    use_full_hex_values_for_flutter_colors: true
    
    # === 命名規則（Dart標準準拠） ===
    file_names: true
    package_names: true
    constant_identifier_names: true
    non_constant_identifier_names: true
    library_names: true
    
    # === Flutter/iOS固有の最適化 ===
    avoid_web_libraries_in_flutter: true
    use_build_context_synchronously: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    
    # === 非同期処理の最適化 ===
    avoid_catching_errors: true
    unawaited_futures: true
    
    # === セキュリティ ===
    avoid_dynamic_calls: true
    
    # === ドキュメンテーション ===
    public_member_api_docs: false  # 個人開発のため無効
    
    # === 実験的・厳格すぎるルールは無効化 ===
    prefer_double_quotes: false
    always_put_control_body_on_new_line: false
    always_specify_types: false  # 型推論を活用
    
    # === Flutter特有の最適化 ===
    avoid_unnecessary_containers: true
    avoid_returning_null_for_void: true
    prefer_relative_imports: true
    
    # === iOS開発での安全性向上 ===
    hash_and_equals: true
    no_adjacent_strings_in_list: true
    prefer_conditional_assignment: true
    prefer_contains: true
    
    # === メモリ効率最適化（iOS重要） ===
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    
    # === CupertinoDesign推奨設定 ===
    # Material固有のウィジェット使用を避ける警告は含まれていないため、
    # 手動でCupertinoウィジェットの使用を推奨する
    
# カスタムルール（必要に応じて追加）
custom_lint:
  # 将来的にカスタムルールを追加する場合はここに記述