name: studyvalue
description: "勉強時間を時給として可視化し、モチベーションを向上させるiOS専用アプリ"
# StudyValue version 1.0.0+1
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 状態管理 - Riverpod
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # ローカルデータベース - Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # iOS用UI
  cupertino_icons: ^1.0.6

  # 通知機能（実際のプロジェクトで使用する場合）
  # flutter_local_notifications: ^16.3.0
  # timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Hive用コード生成
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  # Riverpod用コード生成（将来必要に応じて有効化）
  # riverpod_generator: ^2.3.9
  # riverpod_lint: ^2.3.7

# Flutter設定
flutter:
  uses-material-design: false # iOS専用のためMaterial Designは不使用

  # アセット設定
  assets:
    - assets/images/
    
  # フォント設定（現在はプレースホルダー、実際のフォントファイルが必要）
  # fonts:
  #   - family: NotoSansJP
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/NotoSansJP-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/NotoSansJP-Bold.ttf
  #         weight: 700

# Analyzer設定
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
linter:
  rules:
    # 基本的なlintルール
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false # 開発中のため許可
    
# iOS専用設定のため、Android関連の設定は除外