# StudyValue - iOS専用勉強時間管理アプリ
# 勉強時間を時給として可視化し、モチベーションを向上させる

name: studyvalue
description: "勉強時間を時給として可視化し、モチベーションを向上させるiOS専用アプリ"

# アプリバージョン情報
# version: major.minor.patch+buildNumber
version: 1.0.0+1

# Dart・Flutter環境要件
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.27.0'

# 依存関係（iOS専用構成）
dependencies:
  flutter:
    sdk: flutter

  # 状態管理 - Riverpod（iOS最適化）
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # ローカルデータベース - Hive（オフライン対応）
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # iOS専用アイコン
  cupertino_icons: ^1.0.8

  # 将来の機能拡張用（現在は非使用）
  # flutter_local_notifications: ^17.0.0  # 通知機能
  # timezone: ^0.9.4                      # タイムゾーン処理
  # package_info_plus: ^8.0.0             # アプリ情報取得

# 開発用依存関係
dev_dependencies:
  flutter_test:
    sdk: flutter

  # コード品質管理
  flutter_lints: ^4.0.0

  # Hive用コード生成
  hive_generator: ^2.0.1
  build_runner: ^2.5.1

  # 将来のRiverpod拡張用（必要に応じて有効化）
  # riverpod_generator: ^2.6.1
  # riverpod_lint: ^2.6.1

# Flutter設定（iOS専用最適化）
flutter:
  # Material Designは使用しない（iOS専用のため）
  uses-material-design: false

  # アセット設定
  assets:
    - assets/images/

  # フォント設定（NotoSansJP有効化）
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700

# アナライザー設定（iOS開発最適化）
analyzer:
  exclude:
    # 自動生成ファイルを除外
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    # iOSビルド成果物を除外
    - "ios/Flutter/Generated.xcconfig"
    - "ios/Runner/GeneratedPluginRegistrant.*"
  
  # 厳格な型チェック（品質向上）
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

# Lint設定（iOS開発ベストプラクティス）
linter:
  rules:
    # iOS推奨のコードスタイル
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    
    # 開発効率向上（デバッグ時のprint許可）
    avoid_print: false
    
    # コード品質向上
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    
    # パフォーマンス最適化
    prefer_collection_literals: true
    prefer_spread_collections: true
    
    # 可読性向上
    use_string_buffers: true
    unnecessary_string_interpolations: true
    
    # iOS開発における命名規則
    file_names: true
    package_names: true
    
# iOS専用プラットフォーム設定
# 注意: Android関連の設定は一切含めない